In [ ]:
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig
# from transformers import  GptOssForCausalLM, AutoTokenizer
import torch
import math
import pandas as pd
import json
from tqdm import tqdm
import ast
import nltk
from nltk.corpus import stopwords
import re

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start
    self.io_loop.start()
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 412, in dispatch_shell
    await result
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/scratch/slurm-6228092/ipykernel_1875353/3825229531.py", line 1, in <module>
    import pandas as pd
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 50, in <module>
    from pandas.core import (
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start
    self.io_loop.start()
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 412, in dispatch_shell
    await result
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/scratch/slurm-6228092/ipykernel_1875353/3825229531.py", line 1, in <module>
    import pandas as pd
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/core/arrays/masked.py", line 60, in <module>
    from pandas.core import (
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/core/nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/ihome/xli/sek188/.local/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/software/rhel9/manual/install/python/ondemand-jupyter-python3.11-2023.09/lib/python3.11/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

In [2]:
data = {
    "FH": {
        "main": """NORFOLK — Likening the provisions of the open housing portion of the civil rights package passed by the Senate March 5 to a Robin Hood deed, Oscar F. Baxter IV, president of the 100-real estate firms - represented Norfolk Board of Realtors, urged opposition to the legislation in the House of Representatives.

Claiming non-opposition to integration and open housing as such, Mr. Baxter said that the board had been opposed to what he termed “forced housing” since it was first thought up.

He said, *“It’s still unconstitutional, as far as we are concerned, to take away the rights of one group to give to another.”*

Mr. Baxter stated that the Norfolk Board of Realtors is appealing to, in his words, “congressional representatives all over Virginia, and any others we may have influence with to fight the bill.”

Citing his specific opposition to the bill, Mr. Baxter said, *“Basically the bill denies the home seller, who insists on his traditional freedom of choice in contracting for the sale or rental of his property to whomever he chooses, the use of the professional help he needs from a broker to get the best possible price in the quickest possible time.”*

He continued, “Ostensibly, the bill excludes the home-owner of a single-family home from the provision of the legislation, permitting him to continue to decide without government coercion to whom he will sell or rent. But after Dec 31, 1969, this right is drastically curtailed, and the government can force an unwilling owner to dispose of the house to someone not of his choice if he uses the facilities of any real estate broker or salesman.""",
        "alternate": """The controversial motion picture *“Operation Abolition”* will be shown at the indoctrination session tomorrow. This deals with demonstrations staged last year in San Francisco in connection with hearings held by the House Committee on Un-American Activities.

“All around the nation,” Mr. Powell said today, “a vicious and unrelenting campaign is being carried on to provide by decree, and to enforce by punitive action, a rule that man cannot sell or rent his house to a person or persons of his own choice.”

He termed the antidiscrimination movement a “mounting menace” destined to result in what he called “forced housing.”

“Here is perversion of the traditional and constitutional rights of the American citizen in its most vicious form,” he declared. “Here are the seeds of the breakdown of a free America. Take away rights of property ownership — and human rights become a relic of another age.”"""
    },
    "CAKE": {
        "main": """Where do we think artistic creativity comes from? . . . It's water from the fountain of our soul . . . That's why I say that I'll serve any person, but I won't communicate all messages. Serving people is merely about recognizing each individual as a person worthy of respect, made in the image of God. I'm not trying to force any person to see the world the way I do, or to embrace my beliefs about God and the Bible. If you want to reject Jesus and purchase a cupcake, go ahead. I'll gladly sell you that cupcake, and a cup of coffee to go with it, maybe even engage in a conversation about our differences. But asking me to draw on my creativity to communicate a message I believe is wrong? That's asking me to stop being me. . . . To deny the deepest convictions of my heart, and pretend I haven't learned the most difficult lessons of my life, or that they don't matter. That's not something any person has the right to ask of another. Or a command any government has the right to force one of its citizens to obey.""",
        "alternate": """Phillips was represented by the Alliance Defending Freedom, a legal firm specializing in religious liberty cases. Attorney Nicolle Martin condemned the judge’s ruling.

“America was founded on the fundamental freedom of every citizen to live and work according to their beliefs,” Martin said in a prepared statement. “Forcing Americans to promote ideas against their will undermines our constitutionally protected freedom of expression and our right to live free.

Martin said this was simply a case of a baker who declined to use his personal creative abilities to promote and endorse a same-sex ceremony.

“If the government can take aware our First Amendment freedoms, there is nothing it can’t take away,” she said.

Martin added that Phillips is a devoted Christian who has an unwavering faith. She said he is a person of such deep faith that he won’t even bake Halloween-themed treats – at all.

“He’s just trying to live within a certain set of biblical principals because he believes that he answers to God for everything that he does,” Martin told Fox News.

She said this case is an example of gay rights trumping religious rights.

“It sends a message not just to other business owners, it sends a message to Americans – that if the government can take away our First amendment freedoms and tell you what to say and when to say it, there’s nothing they can’t take away,” Martin told Fox News."""
    }
}

In [3]:

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))


fulldf = pd.DataFrame.from_dict(data, orient='index')
irdf = pd.read_csv("../week15/gpu/interpretive_repertoires.csv")
fulldf = fulldf.stack().reset_index()
fulldf['key'] = fulldf['level_0'] + '_' + fulldf['level_1']
fulldf = fulldf.rename(columns={0: 'text'})
fulldf = fulldf[['key', 'text']]

[nltk_data] Downloading package stopwords to
[nltk_data]     /ihome/xli/sek188/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [4]:
#data sources

def clean_text(text):
    if not isinstance(text, str):
        return ""
    text = text.lower()
    tokens = text.split()
    # tokens = [t for t in tokens if t not in stop_words]
    return " ".join(tokens)

fulldf["charm_article_id"] = fulldf.index + 1

fdf = fulldf[['charm_article_id', 'key',  'text']].copy()

In [5]:
model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
input_text = "The quick brown fox jumps over the lazy dog."

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    dtype=torch.float16,
    device_map="auto"
)
model.eval()

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(32000, 2048)
    (layers): ModuleList(
      (0-21): 22 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=2048, out_features=2048, bias=False)
          (k_proj): Linear(in_features=2048, out_features=256, bias=False)
          (v_proj): Linear(in_features=2048, out_features=256, bias=False)
          (o_proj): Linear(in_features=2048, out_features=2048, bias=False)
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=2048, out_features=5632, bias=False)
          (up_proj): Linear(in_features=2048, out_features=5632, bias=False)
          (down_proj): Linear(in_features=5632, out_features=2048, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm((2048,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((2048,), eps=1e-05)
      )
    )
    (norm): LlamaRMSNorm((2048,), eps=1e-05)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=2048, out_features=32000, bias=False)
)

In [12]:
#stitching and liloing
combined_rows = []
for _, f_row in fulldf.iterrows():
    for _, ir_row in irdf.iterrows():
        combined_row = {
            **f_row.to_dict(),      # all columns from fdf
            **ir_row.to_dict()      # all columns from irdf
        }
        combined_rows.append(combined_row)

cdf = pd.DataFrame(combined_rows)
cdf["attestation"] = cdf["likes"].combine_first(cdf["dislikes"])
cdf["input_text"] = "AUTHOR BIO: \n\n" + cdf["attestation"] + "\n\n" + cdf["text"]
# cdf["input_text"] = cdf["text"]
cdf.drop(columns=['likes', 'dislikes', 'guidewords'])
funkyoutputblocker = None

In [13]:
cdf.head()

,key,text,charm_article_id,IR,bucket,guidewords,likes,dislikes,attestation,input_text
0,FH_main,NORFOLK — Likening the provisions of the open ...,1,Inspired,+,"['righteous', 'pre-ordained', 'beautiful']",I am most deeply moved by things that feel rig...,NaN,I am most deeply moved by things that feel rig...,AUTHOR BIO: \n\nI am most deeply moved by thin...
1,FH_main,NORFOLK — Likening the provisions of the open ...,1,Inspired,-,"['false', 'uncreative', 'dull']",NaN,I have a visceral reaction to anything that st...,I have a visceral reaction to anything that st...,AUTHOR BIO: \n\nI have a visceral reaction to ...

In [13]:
logprobs = []
full_logprobs = []
for idx, row in tqdm(cdf.iterrows(), total=len(cdf)):
    inputs = tokenizer(row['text'], return_tensors="pt").to(model.device)
    # inputs = tokenizer(row['input_text'], return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits

    input_ids = inputs["input_ids"]
    shift_logits = logits[:, :-1, :]
    shift_labels = input_ids[:, 1:]
    log_probs = torch.nn.functional.log_softmax(shift_logits, dim=-1)
    token_log_probs = log_probs.gather(2, shift_labels.unsqueeze(-1)).squeeze(-1)
    average_log_prob = token_log_probs.mean().item()
    logprobs.append(average_log_prob)
    # full_logprobs.append(token_log_probs)

cdf["avg_logprob"] = logprobs
# cdf["logprobs"] = full_logprobs

100%|██████████| 56/56 [00:01<00:00, 48.21it/s]

In [16]:
cdf.head()

,key,text,charm_article_id,IR,bucket,guidewords,likes,dislikes,attestation,input_text,logprob
0,FH_main,NORFOLK — Likening the provisions of the open ...,1,Inspired,+,"['righteous', 'pre-ordained', 'beautiful']",I am most deeply moved by things that feel rig...,NaN,I am most deeply moved by things that feel rig...,AUTHOR BIO: \n\nI am most deeply moved by thin...,-2.390625
1,FH_main,NORFOLK — Likening the provisions of the open ...,1,Inspired,-,"['false', 'uncreative', 'dull']",NaN,I have a visceral reaction to anything that st...,I have a visceral reaction to anything that st...,AUTHOR BIO: \n\nI have a visceral reaction to ...,-2.388672
2,FH_main,NORFOLK — Likening the provisions of the open ...,1,Popular,+,"['preferred', 'popular', 'favorite']",I take comfort in knowing what’s preferred by ...,NaN,I take comfort in knowing what’s preferred by ...,AUTHOR BIO: \n\nI take comfort in knowing what...,-2.386719
3,FH_main,NORFOLK — Likening the provisions of the open ...,1,Popular,-,"['resented', 'feared', 'isolated']",NaN,What unsettles me most is when something or so...,What unsettles me most is when something or so...,AUTHOR BIO: \n\nWhat unsettles me most is when...,-2.380859
4,FH_main,NORFOLK — Likening the provisions of the open ...,1,Moral,+,"['solidary', 'responsible', 'just']",I’m most at ease when I feel like people are l...,NaN,I’m most at ease when I feel like people are l...,AUTHOR BIO: \n\nI’m most at ease when I feel l...,-2.263672

In [15]:
cdf['logprob'].value_counts()
#np.float64(-2.4345703125) - mean
#sd - 0.26353334429045583

logprob
-2.513672    3
-2.390625    2
-2.380859    2
-2.388672    2
-2.365234    2
-2.353516    2
-2.359375    2
-2.263672    1
-2.283203    1
-2.394531    1
-2.316406    1
-2.375000    1
-2.343750    1
-2.488281    1
-2.529297    1
-2.386719    1
-2.507812    1
-2.425781    1
-2.515625    1
-2.556641    1
-2.675781    1
-2.464844    1
-2.480469    1
-2.525391    1
-2.691406    1
-2.363281    1
-2.349609    1
-2.212891    1
-2.275391    1
-2.232422    1
-2.501953    1
-2.296875    1
-2.335938    1
-2.511719    1
-2.191406    1
-2.195312    1
-2.205078    1
-2.208984    1
-2.064453    1
-2.134766    1
-2.201172    1
-2.078125    1
-2.179688    1
-2.197266    1
-2.306641    1
-2.146484    1
-2.169922    1
-2.337891    1
Name: count, dtype: int64

In [14]:
cdf.to_csv("raw_coh_scores.csv")